# Generated by Django 4.0.4 on 2022-08-19 11:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etalon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etalon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='etalonproperty',
            name='etalon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etalon_properties', to='back.etalon'),
        ),
    ]
